# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://IcaRiBe.github.io/toefl_test/"

git_url = "https://github.com/IcaRiBe/toefl_test/tree/master/"

def custom_doc_links(name): return None
